name = "AJD"
uuid = "554d0510-86f8-456b-923c-97159df4572d"
authors = ["Nicholas Gericke <nicholas.gericke@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[deps]
Diagonalizations = "9cd687f3-b62d-43f3-8fd3-ffcd9e581047"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PosDefManifold = "f45a3650-5c51-11e9-1e9a-133aa5e309cf"

[compat]
Diagonalizations = "0.2.3"
LinearAlgebra = "1.11.0"
PosDefManifold = "0.5.1"
julia = "1.10"
