name = "AJD"
uuid = "554d0510-86f8-456b-923c-97159df4572d"
authors = ["Nicholas Gericke <nicholas.gericke@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[deps]
Diagonalizations = "9cd687f3-b62d-43f3-8fd3-ffcd9e581047"

[compat]
Diagonalizations = "0.2.3"
julia = "1.10"
