name = "AJD"
uuid = "554d0510-86f8-456b-923c-97159df4572d"
authors = ["Nicholas Gericke <nicholas.gericke@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
PyCall = "1.96.4"
Test = "1.11.0"
julia = "1.10"
